apiVersion: 1

datasources:
  - name: MFP_PostgreSQL
    type: postgres
    uid: mfp-postgres-ds
    url: postgres:5432
    database: ${POSTGRES_DB:-mfp_data}
    user: ${POSTGRES_USER:-mfp_user}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-mfp_password}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
